### ISSUE TITLE
Find out why some Android users get stuck on "Decrypting notes..."

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#21]
This one is more of a QA bounty. We're not looking for any actual code, but instead just a set of steps that would allow us to replicate this issue. 

There seems to be some subset of Android users who either:

1. Experience a large slowdown on initial decrypt on app launch. Loading 1000 notes and tags, for example, should take no more than 2-3 seconds. For some users, it takes 50-60 seconds. Something's obviously going on here. 

   Issue here: https://github.com/standardnotes/mobile/issues/101

   Note also that when I created a dummy account with just notes, these same users said they did not experience any slowdown. So it might be something to do with resolving tags and other relationships.

2. Get completely stuck on "Decrypting notes..." screen. 

   Issue here: https://github.com/standardnotes/forum/issues/365

I've tried to replicate either of these issues, but have not been able to. I've yet to determine whether this is an account related issue (data specific), or device issue.

The goal would be to replicate either of these issues (they might be related) and provide clear steps (or even credentials to a test account) that would also allow me to replicate them.

**Comment by jonhadfield** [comment]
- After exporting and importing I still had the same, 'slow decryption' issue.
- After replacing the content (tag and note titles with the item UUID, and note text with the letter 'b' replacing every existing character so retaining the same number of chars) the issue has disappeared. Note: all other item data including AppData and ItemReferences remained intact.

It would suggest that, for some strange reason, the decryption speed is based on the the content that has been encrypted.

**Comment by jonhadfield** [comment]
After exporting and importing again, I deleted the tag called 'evernote' (automatically set for each note imported from evernote) and the issue has gone away!
Is the android app processing tags with many items in a different way?

**Comment by mobitar** [comment]
The Android app doesn't do anything different from web/desktop in terms of processing items. They use the same exact code actually. It may just be that the OS isn't fine-tuned for some operations. Can you provide either a backup file or dummy account credentials so I can try to replicate this?

**Comment by jonhadfield** [comment]
I'm attempting to obfuscate a copy of my content so I can share with you.
In the meantime I've discovered that:
- Importing the backup to my own SN (ruby) server results in a very fast load on Android app
- When logging in with the desktop (latest on macOS) app, I get the same, slow, load time as seen on Android app...
Here's a screenshot showing how long it's taking to download the content:
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/843944/49892524-19900b80-fe41-11e8-9028-0ed8c5916063.png">
I've got a 40M+ broadband connection, so I can only think either your server is slow (unlikely) or there's something about the data that is causing the client apps to download. I've shared a link to a video of the login and download via Slack PM.

**Comment by mobitar** [comment]
The original issues seem to be local, in that the data is already downloaded, but loading them up locally experiences a slowdown. That would be a plot twist though, if the reason was that the data was being redownloaded from the server. Very unlikely though.

The server slowdown is an issue of its own, if this is consistent. I haven't heard any reports of this. Is this something new for you?

**Comment by quartertone** [comment]
Experiencing this same issue.
I have 2500+ notes (imported from Evernote), with 50+ tags (some duplicated due to the import process).
Android SN app version 2.3.10 on OnePlus 5T with Android 8.1.0
After having loaded all the notes (initial decrypting complete), I press the "Back" button on my device to exit the app. Re-opening the app causes an initial flood of cached notes, and then "Decrypting xxxx/xxxx items ..." shows at the bottom of the screen for several minutes (~7-10+) while everything loads up fully. Same thing occurs after I press the "Recents" button to bring up the active app list, and swipe away the app to close it; re-opening the app causes decryption to start all over.

Decryption speed seems to slow down as it continues. First ~500 items go at about 100/second, but after that it progressively slows to almost 2-3 minutes per 100 items.

The issue does not seem to be a re-downloading issue. The problem occurs even with the network connection off.

The same decryption slowdown seems to be happening with the desktop app (Linux version 3.0.1) and the web app, though to a lesser extent. I think it takes about half the time on desktop & web app, but it's still quite slow.

**Comment by mobitar** [comment]
Got it, thanks for the info @quartertone. I think we've successfully narrowed this issue down to tag resolution. Tags with many hundred notes will cause this problem. This issue will be addressed in the next update, which I'm currently working on (pending reproducibility, which I'm hoping will be easy now that we've whittled it down).

**Comment by mobitar** [comment]
This should be fixed in the 3.0 beta: https://play.google.com/apps/testing/com.standardnotes
