### ISSUE TITLE
Add synced scroll to Simple Markdown Editor

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#22]
In Split mode, when you scroll the left side, it should scroll the right side.

The [Advanced Markdown Editor](https://github.com/sn-extensions/advanced-markdown-editor) and the [Fancy Markdown Editor](https://github.com/sn-extensions/fancy-markdown-editor) already do this. Perhaps study that code for inspiration?

Links:
https://github.com/sn-extensions/simple-markdown-editor

**Comment by bryvin** [comment]
I think this is a feature of SimpleMDE and the Upmath Editors and not just CodeMirror but I could be wrong... though I didn't see this in any CodeMirror docs. Definitely I'm sure it's possible to implement our own solution here, but a problem even with those existing ones is they are easily able to be "out of sync". Meaning the 2 panels can be completely offset from one another due to the height of the content in the preview vs the text version.

This is basically not possible to fix unless you somehow made a way line up 1 line with it's computed output in the preview panel, but that'd leave big gaps in between the lines of the text version. Which could look odd, and would most likely be difficult to implement into CodeMirror.

For example, if you had assets in the preview that loaded in or big font; it would be much taller than the text copy where the lines are all the same height. 

This is a similar problem to how we talked about saving the offset of where you left off when you switch notes. It's hard to do with the variables at play:

- content height
- width of panels
- width of editor
- font size
- etc

Do you have any ideas or maybe you don't care if they line up entirely, but would prefer they just scroll at the same time? 

Personally not sure how useful that is if they aren't lined up exactly.

**Comment by mobitar** [comment]
It seems like the synced scroll feature in the current editors is sort of an approximation. I think some sync is better than no sync, is the solution we would go for here.

**Comment by dagjaneiro** [comment]
This seems like a good first issue to tackle, can I give it a shot?

**Comment by mobitar** [comment]
@dagjaneiro Yup, go for it!
