### ISSUE TITLE
Replicate scenario where uninstalling Android app does not delete application data

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#30]
There seems to be a relatively [new issue](https://github.com/standardnotes/forum/issues/556) where uninstalling the Android app, then re-installing, does not appear to delete old application data. The result is that the user stays signed in. This is somewhat bewildering, given that deleting the application off Android should delete its data directory, without any input from us.

I have been unable to reproduce this issue. About 3-4 users in total have reported it, and they seem to share the characteristic that they downloaded the app from Google Play, but also downloaded the app via another source, like F-Droid, or the Google Play Beta program.

This is quite an important issue, and I'll be investigating this myself. But thought I'd create a bounty as well to maximize the chance that we get this issue replicated. Your goal with this bounty is to summarize the steps that lead to this result. Once I can consistently replicate this, exploring a fix will be much easier.

One potential lead is that we recently updated our app to use the [react-native-async-storage](https://github.com/react-native-community/react-native-async-storage) package instead of using the built-in AsyncStorage from React Native, as the built in method has been deprecated in favor of this package.

**Comment by dagjaneiro** [comment]
In the issue, you said you were able to replicate it via F-Droid on your cellphone, not in an emulator. Is the purpose of this bounty to replicate it in an emulator?

**Comment by mobitar** [comment]
Well, the purpose is to find out exactly what causes this, so that it's replicable anywhere, on emulator and on device. But yeah, assuming the steps are concrete, then the issue should occur on the emulator just as it would occur on device.

**Comment by dagjaneiro** [comment]
I was finally able to replicate this.

The key to this issue lies in Android's auto backup settings (In Android 9 it's under Settings -> System -> Backup -> App data). If you have it turned on Android will backup your app's data to google drive so that you can restore all your apps configurations if you change phones. 

When the app is uninstalled and installed through the **Play store** (or even running the **Apk**) with this setting turned on it seems the installation process is smart enough to know that it shouldn't recover the settings from the backup since the app was just uninstalled from this system. 

When we do the same through **F-Droid** it will recover the previously backed up configurations for **Standard Notes**, including all notes and credentials. 

Furthermore, even if we force a backup after uninstalling the application so that the app no longer appears in the list of backed up app data **F-Droid** will be able to retrieve the configurations that were previously backed up. 

To prevent **F-Droid** from recovering the data when installing the app the **automatic restore** setting under **app data** needs to be disabled. Alternatively, if the backup option is disabled and enabled again the previous backup will be deleted from google drive which also works.

![image](https://user-images.githubusercontent.com/10207818/59803923-df6a5f80-92e4-11e9-8f73-81172332a3b4.png)

This issue can be replicated successfully independently of the **Standard Notes** version.

## Steps to replicate
1. Install any version of Standard Notes
2. Login in the app
3. Go to Backup Settings in Android (Settings -> System -> Backup), turn it **on** for **App data** and press **Back up now**. Wait for it to finish the backup
4. Uninstall Standard Notes
5. Reinstall Standard Notes through F-Droid
6. Your previous session and notes will be recovered

## Steps to resolve for users facing the issue
1. Uninstall Standard Notes
2.  Go to Backup Settings in Android (Settings -> System -> Backup), turn it **off** for **App data**
3. Reinstall the app

## Possible solution

I would suggest we disable the auto backup option for **Standard Notes** as I can't think of a scenario where this behaviour would be desirable. 

We can achieve this by [setting the autoBackup option in the manifest to false](https://developer.android.com/guide/topics/data/autobackup#EnablingAutoBackup). 

This should fix the issue in **F-Droid** as the app data will no longer be available in the backup.

**Comment by mobitar** [comment]
The reason we allowBackup is so that if a user gets a new device and restores the device from a previous backup of their other device, we want their notes data to be restored. I'll have to look more into this.

But bingo on the summary. Was able to confirm your steps. Thanks for investigating!
