### ISSUE TITLE
Sign in and Register button render without height in the web app when using ChromeOS/Chromebook

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#33]
https://github.com/standardnotes/forum/issues/576

I've received this report from another user as well who was able to inspect element and set a manual height, and the buttons appeared.

**Comment by dagjaneiro** [comment]
FYI I tried replicating this in [cloudready](https://www.neverware.com) (the closest thing I could find to ChromeOS that could be virtualized) and I was unable to replicate the issue.

Also, not sure if it matters, but the version reported for chrome is not the [current stable version](https://omahaproxy.appspot.com/) but the dev/beta version.

I guess the only way to replicate this would be to have an actual Chromebook 😞

**Comment by mobitar** [comment]
Hmm ok, thanks for trying!

**Comment by ExpandingFoam** [comment]
Hi Just thought I'd let you know this is now resolved (for me), because it's still "open". 

My current Chrome is 76.0.3809.20 (Official Build) dev (32-bit). 

I have been playing around with a few plugins lately like uBlock Origin and Privacy Badger, and also the browser settings for content. I don't know how this works but poss something interfered? 

I'm trying to get rid of my chromebook; I just need to figure out what to replace it with. Maybe you want it when I've done that? Its perfectly fine other being totally infested with Google. 

Meantime if there is any specific test I could do help troubleshoot? I could fiddle with some numbers if it helps.

**Comment by mobitar** [comment]
Ah, you know what, it may have been a browser extension interfering with the styling of that element. Was it you that emailed me about this issue as well? Because in that case it could have been just 1 person sample size and not 2. In any case I'll mark this closed for now.

**Comment by ExpandingFoam** [comment]
Hello, sorry I thought I replied to this already but seems not. 
I did NOT email you about it. 
n = 2 :)
