### ISSUE TITLE
Simple Task Editor Windows font

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#9]
On Windows, the Simple Task Editor font is very thin. Only seems to be the case in the Windows desktop app (not web). 

Links:
- https://github.com/sn-extensions/simple-task-editor

Related tasks:
- https://github.com/standardnotes/bounties/issues/8

**Comment by bryvin** [comment]
By thin do you just mean like the image below I took on a Windows VM? If so I think it's just because the 'monospace' font that gets renders is just dependent on what is on the persons computer as an installed font (this VM I used is a fresh install of Windows 10 with no additional fonts installed.. it may be different for other users or computers). The only way to fix that I think would be to pick one that all systems have (not sure if there is a list for this) or maybe include a font in the dist to import with the extension/editor. 

The font-weight is already normal, so it really just depends on the font face rendered.

![mc0rsmh](https://user-images.githubusercontent.com/5969300/49249425-11b87c00-f3ea-11e8-9095-919a4aaa936b.png)

**Comment by mobitar** [comment]
Yup. Honestly, I think it may just be as simple as doing this: https://github.com/standardnotes/desktop/blob/master/app/index.html#L158

Because this issue used to exist for the built in editor on Windows, and that fixed it.

**Comment by mobitar** [comment]
Although if you look on Mac, the font is sans-serif default, like Helvetica or something. So not sure why Windows is monospace. Maybe `font-family: sans-serif;` will do the trick.

<img width="660" alt="screen shot 2018-11-30 at 9 15 08 am" src="https://user-images.githubusercontent.com/3277844/49297468-758d8400-f480-11e8-84d4-414abf0315f0.png">

**Comment by bryvin** [comment]
If I remember correctly sans-serif was crossed out from a different rule.. but probably just ordering. 

I’ll check a bit later today if you’d like me to.

**Comment by bryvin** [comment]
You hater :)

Sounds good though.. should be simple like you said.

**Comment by mobitar** [comment]
Easiest $75 of my life :) https://github.com/sn-extensions/simple-task-editor/commit/797e3e3cf44c59203cea51111a1987f7d10c28b3#diff-aed68324decf61f0496113e65491e7f3R30
